- name: Checking overcloud_deploy_file
  stat:
      path: "~/overcloud_deploy.sh"
  register: overcloud_deploy_file

- fail:
      msg: "Overcloud deployment script not found. Expected path: ~/overcloud_deploy.sh "
  when: not overcloud_deploy_file.stat.exists

- fail:
      msg: "--scale-nodes is required"
  when: install.get('scale', {}).nodes is not defined
