- include_tasks: preliminary_checks.yml
  when:
    - rc_preliminary_checks | bool

- include_tasks: remove_ceph_monitor.yml
  when:
      - rc_remove_ceph_monitor | bool
      - "'ceph' in groups"

- include_tasks: manual_preparation.yml
  when:
    - rc_manual_preparation | bool

- include_tasks: replace_node.yml
  when:
    - rc_replace_node | bool

# Update galera pacemaker resource parameter manually
# This step is valid on OSP releases older than 14
- include_tasks: manual_intervention.yml
  when:
    - rc_manual_intervention | bool
    - install.version|default(undercloud_version)|openstack_release < 14

- include_tasks: finalize.yml
  when:
    - rc_finalize | bool

# Add new replaced controller node to instackenv file for future use
# (i.e. The file is used for fencing configuration)
- include_tasks: update_instackenv.yml
  when:
    - overcloud_replace is defined
    - overcloud_replace.rc == 0
    - not install.use.the.same.node|bool
